//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppEntity : DbContext
    {
        public AppEntity()
            : base("name=AppEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_company> m_company { get; set; }
        public virtual DbSet<m_employee> m_employee { get; set; }
        public virtual DbSet<m_menu> m_menu { get; set; }
        public virtual DbSet<m_menu_access> m_menu_access { get; set; }
        public virtual DbSet<m_product> m_product { get; set; }
        public virtual DbSet<m_role> m_role { get; set; }
        public virtual DbSet<m_souvenir> m_souvenir { get; set; }
        public virtual DbSet<m_unit> m_unit { get; set; }
        public virtual DbSet<m_user> m_user { get; set; }
        public virtual DbSet<t_design> t_design { get; set; }
        public virtual DbSet<t_design_item> t_design_item { get; set; }
        public virtual DbSet<t_design_item_file> t_design_item_file { get; set; }
        public virtual DbSet<t_event> t_event { get; set; }
        public virtual DbSet<t_promotion> t_promotion { get; set; }
        public virtual DbSet<t_promotion_item> t_promotion_item { get; set; }
        public virtual DbSet<t_promotion_item_file> t_promotion_item_file { get; set; }
        public virtual DbSet<t_souvenir> t_souvenir { get; set; }
        public virtual DbSet<t_souvenir_item> t_souvenir_item { get; set; }
    }
}
