//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_design_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_design_item()
        {
            this.t_design_item_file = new HashSet<t_design_item_file>();
            this.t_promotion_item = new HashSet<t_promotion_item>();
        }
    
        public int id { get; set; }
        public int t_design_id { get; set; }
        public int m_product_id { get; set; }
        public string title_item { get; set; }
        public int request_pic { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> request_due_date { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_active { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual m_employee m_employee { get; set; }
        public virtual m_product m_product { get; set; }
        public virtual t_design t_design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_design_item_file> t_design_item_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_promotion_item> t_promotion_item { get; set; }
    }
}
