//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_promotion_item_file
    {
        public int id { get; set; }
        public int t_promotion_id { get; set; }
        public string filename { get; set; }
        public string size { get; set; }
        public string extension { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> request_due_date { get; set; }
        public Nullable<long> qty { get; set; }
        public int todo { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_active { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual t_promotion t_promotion { get; set; }
    }
}
