//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_souvenir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_souvenir()
        {
            this.t_souvenir_item = new HashSet<t_souvenir_item>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public Nullable<int> t_event_id { get; set; }
        public int request_by { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<System.DateTime> request_due_date { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<int> received_by { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<int> settlement_by { get; set; }
        public Nullable<System.DateTime> settlement_date { get; set; }
        public Nullable<int> settlement_approved_by { get; set; }
        public Nullable<System.DateTime> settlement_approved_date { get; set; }
        public Nullable<int> status { get; set; }
        public string note { get; set; }
        public string reject_reason { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual m_employee m_employee { get; set; }
        public virtual m_employee m_employee1 { get; set; }
        public virtual m_employee m_employee2 { get; set; }
        public virtual m_employee m_employee3 { get; set; }
        public virtual m_employee m_employee4 { get; set; }
        public virtual t_event t_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_souvenir_item> t_souvenir_item { get; set; }
    }
}
